== systemz

image::https://api.bintray.com/packages/mbbx6spp/maven/systemz/images/download.svg[link="https://bintray.com/mbbx6spp/maven/systemz/_latestVersion"]

=== Purpose

A scalaz style project providing a way to functionally wrap system level JVM
requirements like writing Java Agents, extending or inspecting JMX,
interfacing with class loaders, etc.

=== Status

We just started the project. Please wait while we move in here. Cheers!

image:https://travis-ci.org/functionalops/systemz.svg?branch=master["Build Status", link="https://travis-ci.org/functionalops/systemz"]

=== License

This will be licensed under the BSD 3-clause license. See link:LICENSE[].

=== Prerequisites

1. Java 8
2. Scala 2.11.4
3. SBT 0.13.0+

=== Getting Started

Inside the root directory of the repository:

1. Launch SBT:

        $ sbt

2. Compile everything and run all tests:

        > test

=== Subprojects

The following are subprojects of this parent project:

* link:core[] - functional abstractions for JMX, JavaAgent, Instrumentation &
  related core Java APIs.
* link:cloud[] - APIs for (public) cloud providers to query resources.
* link:examples[] - executable examples and system level checks.
* link:management[] - ???
